import {
  MdFlight,
  MdHotel,
  MdDirectionsCar,
  MdTour,
} from "react-icons/md";

export const MOCK_DATA = {
  avia: {
    headers: [
      "Авиакомпания",
      "Рейс",
      "Маршрут",
      "Вылет / Прибытие",
      "В пути",
      "Пересадки",
      "Багаж",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        airline: "Аэрофлот",
        flightNumber: "SU 1234",
        route: "MOW - DXB",
        departureTime: "18:45",
        arrivalTime: "23:00",
        departureLocation: "Париж (CDG)",
        duration: "4ч 15м",
        connections: "Прямой",
        baggage: "23 кг",
        price: "45 800 ₽",
        pricePerPerson: "за чел.",
        totalPrice: "91 600 ₽",
        tariffType: "Эконом Оптимум",
        tariffRules: {
          refund: "С удержанием сбора",
          exchange: "Бесплатно до вылета",
          baggage: "23 кг + 10 кг ручная кладь",
        },
        passengers: [
          { name: "Иван Петров", type: "Взрослый", birthDate: "12.05.1985", tariff: "Эконом" },
          { name: "Анна Петрова", type: "Взрослый", birthDate: "23.08.1990", tariff: "Эконом" },
        ],
        segments: [
          {
            from: "Москва (SVO)",
            to: "Дубай (DXB)",
            departure: "10:45",
            arrival: "15:00",
            duration: "4ч 15м",
            flight: "SU214",
            aircraft: "A320",
          },
          {
            from: "Дубай (DXB)",
            to: "Стамбул (IST)",
            departure: "16:30",
            arrival: "19:45",
            duration: "3ч 15м",
            flight: "TK514",
            aircraft: "B737",
          },
        ],
      },
      {
        id: 2,
        airline: "Emirates",
        flightNumber: "EK 132",
        route: "MOW - DXB",
        departureTime: "23:50",
        arrivalTime: "06:15",
        departureLocation: "Москва (DME)",
        duration: "5ч 25м",
        connections: "Прямой",
        baggage: "30 кг",
        price: "68 500 ₽",
        pricePerPerson: "за чел.",
        totalPrice: "137 000 ₽",
        tariffType: "Flex Plus",
        tariffRules: {
          refund: "Полный возврат",
          exchange: "Бесплатно",
          baggage: "30 кг + 7 кг ручная кладь",
        },
        passengers: [
          { name: "Иван Петров", type: "Взрослый", birthDate: "12.05.1985", tariff: "Эконом" },
          { name: "Анна Петрова", type: "Взрослый", birthDate: "23.08.1990", tariff: "Эконом" },
        ],
        segments: [
          {
            from: "Москва (DME)",
            to: "Дубай (DXB)",
            departure: "23:50",
            arrival: "06:15",
            duration: "5ч 25м",
            flight: "EK132",
            aircraft: "A380",
          },
        ],
      },
    ],
  },
  train: {
    headers: [
      "Перевозчик",
      "Поезд",
      "Маршрут",
      "Отправление / Прибытие",
      "В пути",
      "Тип вагона",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        carrier: "РЖД",
        trainNumber: "002А",
        trainName: "Красная Стрела",
        route: "Москва → Санкт-Петербург",
        departureTime: "23:55",
        arrivalTime: "07:55",
        duration: "8ч 00м",
        departureDate: "14 июня",
        stations: "Ленинградский вокзал → Московский вокзал",
        services: ["Wi-Fi", "Кондиционер", "Питание", "Биотуалет"],
        carType: "Купе",
        price: "4 500 ₽",
        cars: [
          {
            id: 1,
            number: "05",
            type: "Купе",
            cls: "2Э",
            carrier: "ФПК",
            freeSeats: 12,
            priceRange: "4 500 - 5 200 ₽",
            services: ["ac", "food", "wifi"],
            schema: {
              type: "coupe",
              seats: Array.from({ length: 36 }, (_, i) => ({
                number: i + 1,
                type: i % 2 === 0 ? "lower" : "upper",
                price: i % 2 === 0 ? "5 200 ₽" : "4 500 ₽",
                isFree: Math.random() > 0.3,
              })),
            },
          },
          {
            id: 2,
            number: "06",
            type: "Купе",
            cls: "2Э",
            carrier: "ФПК",
            freeSeats: 4,
            priceRange: "4 500 - 5 200 ₽",
            services: ["ac", "food", "wifi"],
            schema: {
              type: "coupe",
              seats: Array.from({ length: 36 }, (_, i) => ({
                number: i + 1,
                type: i % 2 === 0 ? "lower" : "upper",
                price: i % 2 === 0 ? "5 200 ₽" : "4 500 ₽",
                isFree: Math.random() > 0.5,
              })),
            },
          },
          {
            id: 3,
            number: "08",
            type: "СВ",
            cls: "1Б",
            carrier: "ФПК",
            freeSeats: 8,
            priceRange: "12 500 ₽",
            services: ["ac", "food", "wifi", "tv"],
            schema: {
              type: "sv",
              seats: Array.from({ length: 18 }, (_, i) => ({
                number: i + 1,
                type: "lower",
                price: "12 500 ₽",
                isFree: Math.random() > 0.2,
              })),
            },
          },
        ],
      },
      {
        id: 2,
        carrier: "РЖД",
        trainNumber: "004А",
        trainName: "Экспресс",
        route: "Москва → Санкт-Петербург",
        departureTime: "23:30",
        arrivalTime: "08:30",
        duration: "9ч 00м",
        departureDate: "14 июня",
        stations: "Ленинградский вокзал → Московский вокзал",
        services: ["Wi-Fi", "Кондиционер"],
        carType: "СВ",
        price: "12 500 ₽",
        cars: [],
      },
    ],
  },
  hotel: {
    headers: [
      "Отель",
      "Звезды",
      "Расположение",
      "Даты",
      "Ночей",
      "Тип номера",
      "Гостей",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        name: "Hilton Istanbul Bosphorus",
        stars: "5★",
        location: "Стамбул, Центр",
        checkIn: "14.06",
        checkOut: "19.06",
        nights: "5 ночей",
        roomType: "Deluxe Room",
        guests: "2 взр",
        price: "67 500 ₽",
        pricePerNight: "13 500 ₽",
        rating: "4.8",
        address: "Cumhuriyet Caddesi Harbiye, 34367 Istanbul",
        description: "Роскошный отель с видом на Босфор, расположенный в самом сердце Стамбула. К услугам гостей спа-центр, открытый бассейн и 6 ресторанов.",
        amenities: ["Wi-Fi", "Бассейн", "СПА", "Завтрак", "Парковка"],
        rooms: [
          { type: "Standard", meals: "Завтрак", cancellation: "Бесплатно до 12.06", price: "67 500 ₽" },
          { type: "Deluxe", meals: "Завтрак + Ужин", cancellation: "Бесплатно до 12.06", price: "82 000 ₽" },
        ],
      },
      {
        id: 2,
        name: "Swissotel The Bosphorus",
        stars: "5★",
        location: "Стамбул, Бешикташ",
        checkIn: "14.06",
        checkOut: "19.06",
        nights: "5 ночей",
        roomType: "Swiss Advantage",
        guests: "2 взр",
        price: "85 200 ₽",
        pricePerNight: "17 040 ₽",
        rating: "4.9",
        address: "Visnezade Mah. Acisu Sok. No:19 Macka, Besiktas",
        description: "Отель класса люкс с панорамным видом на Босфор. Идеальное расположение рядом с дворцом Долмабахче.",
        amenities: ["Wi-Fi", "Бассейн", "Фитнес", "Ресторан на крыше"],
        rooms: [
          { type: "Advantage", meals: "Завтрак", cancellation: "Бесплатно до 10.06", price: "85 200 ₽" },
        ],
      },
    ],
  },
  transfer: {
    headers: [
      "Поставщик",
      "Маршрут",
      "Класс",
      "Вместимость",
      "Время",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        supplier: "KiwiTaxi",
        route: "Аэропорт (IST) → Отель",
        carClass: "Comfort",
        capacity: "4 чел, 3 багажа",
        duration: "45 мин",
        price: "4 200 ₽",
        cars: [
          { class: "Economy", passengers: "3 чел", luggage: "2 места", price: "3 500 ₽" },
          { class: "Comfort", passengers: "4 чел", luggage: "3 места", price: "4 200 ₽" },
          { class: "Minivan", passengers: "7 чел", luggage: "7 мест", price: "6 800 ₽" },
        ],
      },
    ],
  },
  visa: {
    headers: [
      "Страна",
      "Сроки",
      "Документы",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        country: "Турция",
        terms: "5-7 рабочих дней",
        docs: "Паспорт, фото, анкета",
        price: "15 000 ₽",
        process: "Подача в визовом центре, личное присутствие не требуется.",
        tariffs: [
          { type: "Стандартная", term: "7 дней", price: "15 000 ₽" },
          { type: "Срочная", term: "3 дня", price: "25 000 ₽" },
        ],
      },
    ],
  },
  insurance: {
    headers: [
      "Компания",
      "Покрытие",
      "Срок",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        company: "АльфаСтрахование",
        coverage: "до 50 000 €",
        term: "14 дней",
        price: "2 500 ₽",
        includes: ["Медицинские расходы", "Транспортировка", "Стоматология (экстренная)"],
        options: [
          { sum: "30 000 €", sport: "Нет", price: "1 800 ₽" },
          { sum: "50 000 €", sport: "Нет", price: "2 500 ₽" },
          { sum: "100 000 €", sport: "Да", price: "5 200 ₽" },
        ],
      },
    ],
  },
  tour: {
    headers: [
      "Экскурсия",
      "Дата и время",
      "Длительность",
      "Человек",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        name: "Обзорная по Стамбулу",
        dateTime: "15.06.2024, 10:00",
        duration: "4 часа",
        pax: "2 чел",
        price: "12 000 ₽",
        route: "Площадь Султанахмет → Голубая мечеть → Айя-София → Гранд Базар",
        includes: ["Лицензированный гид", "Трансфер от отеля", "Входные билеты"],
        details: [
          { block: "Маршрут", description: "Султанахмет - Айя-София - Гранд Базар" },
        ],
      },
    ],
  },
  taxi: {
    headers: [
      "Сервис",
      "Маршрут",
      "Длительность",
      "Класс",
      "Пассажиры",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        service: "Яндекс.Такси",
        route: "Отель → Аэропорт",
        duration: "45 мин",
        carClass: "Business",
        pax: "3 чел",
        price: "3 500 ₽",
        classes: [
          { class: "Economy", passengers: "3 чел", price: "1 200 ₽" },
          { class: "Comfort", passengers: "4 чел", price: "1 800 ₽" },
          { class: "Business", passengers: "3 чел", price: "3 500 ₽" },
        ],
      },
    ],
  },
  lounge: {
    headers: [
      "Бизнес-зал",
      "Терминал",
      "Доступ",
      "Цена",
      "Действие",
    ],
    items: [
      {
        id: 1,
        name: "Business Lounge East",
        terminal: "Терминал D",
        accessTime: "3 часа",
        price: "3 500 ₽",
        restrictions: "Дресс-код: Smart Casual. Дети до 2 лет бесплатно.",
        conditions: [
          { item: "Зона питания", value: "Шведский стол" },
          { item: "Душевые", value: "Есть" },
          { item: "Wi-Fi", value: "Бесплатный" },
          { item: "Алкоголь", value: "Включен" },
        ],
      },
    ],
  },
};

export const SELECTED_SERVICES = [
  {
    id: "avia_1",
    type: "Авиабилет",
    details: "Москва → Стамбул",
    time: "15 июня 2024, 10:30 → 14:45 (местное время)",
    description: "Turkish Airlines TK 414 • Эконом • 3ч 15мин",
    price: "32 450 ₽",
    pax: "3 пассажиров",
    icon: MdFlight,
  },
  {
    id: "hotel",
    type: "Отель",
    details: "Hilton Istanbul Bosphorus",
    time: "15 июня — 22 июня 2024 • 7 ночей",
    description: "Deluxe Room • 2 взрослых, 1 ребёнок",
    price: "89 600 ₽",
    pax: "7 ночей",
    icon: MdHotel,
  },
  {
    id: "tour",
    type: "Экскурсия",
    details: "Обзорная экскурсия по Стамбулу",
    time: "18 июня 2024, 09:00 • 8 часов",
    description: "Групповая экскурсия • Русскоязычный гид • 3 персоны",
    price: "12 900 ₽",
    pax: "за группу",
    icon: MdTour,
  },
  {
    id: "avia_2",
    type: "Авиабилет",
    details: "Обратный перелёт Стамбул → Москва",
    time: "22 июня 2024, 16:20 → 20:35 (местное время)",
    description: "Turkish Airlines TK 415 • Эконом • 3ч 15мин",
    price: "34 800 ₽",
    pax: "3 пассажиров",
    icon: MdFlight,
  },
];
