import {
  MdDashboard,
  MdDescription,
  MdPayment,
  MdAssignmentReturn,
  MdPeople,
  MdBusiness,
  MdCurrencyExchange,
  MdAccountBalance,
  MdBarChart,
  MdNotifications,
  MdHistory,
  MdSyncAlt,
  MdChat,
} from "react-icons/md";

export const accountantMenuItems = [
  {
    id: "dashboard",
    label: "Дашборд",
    icon: MdDashboard,
    href: "/accountant",
  },
  {
    id: "documents",
    label: "Документы",
    icon: MdDescription,
    href: "/accountant/document",
  },
  {
    id: "finance",
    label: "Финансы",
    icon: MdAccountBalance,
    href: "/accountant/finance",
  },
  {
    id: "suppliers-payouts",
    label: "Выплаты поставщикам",
    icon: MdBusiness,
    href: "/accountant/suppliers",
  },
  {
    id: "payments",
    label: "Платежи",
    icon: MdPayment,
    href: "/accountant/payments",
  },
  {
    id: "returns",
    label: "Возвраты",
    icon: MdAssignmentReturn,
    href: "/accountant/refunds",
  },
  {
    id: "currency",
    label: "Валюты и курсы",
    icon: MdCurrencyExchange,
    href: "/accountant/currency",
  },
  {
    id: "reports",
    label: "Отчёты",
    icon: MdBarChart,
    href: "/accountant/reports",
  },
  {
    id: "notifications",
    label: "Уведомления",
    icon: MdNotifications,
    href: "/accountant/notifications",
  },
  {
    id: "activity-log",
    label: "Журнал действий",
    icon: MdHistory,
    href: "/accountant/activity-log",
  },
  {
    id: "import-export",
    label: "Импорт / экспорт",
    icon: MdSyncAlt,
    href: "/accountant/import-export",
  },
  {
    id: "employees",
    label: "Операторы",
    icon: MdPeople,
    href: "/accountant/employees",
  },
  {
    id: "chat",
    label: "Чат",
    icon: MdChat,
    href: "/accountant/chat",
  },
];
